version: '3.8'
services:
  node-test:
    container_name: ntrb-nodejs-test
    image: ntrb-nodejs-test-image
    build:
      context: ./
      dockerfile: ./src/app/node-server/Dockerfile
    depends_on:
      - mongo-test
    ports:
      - ${PORT}:${PORT}
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED}
      - NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED}
    networks:
      - ntrb-test

  mongo-test:
    container_name: ntrb-mongodb-test
    image: ntrb-mongodb-test-image
    build:
      context: ./
      dockerfile: ./src/app/mongo-server-test/Dockerfile
    networks:
      - ntrb-test

networks:
  ntrb-test: